apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: niraj1405/dockercomposevolumeimage:1.0.0-109
          ports:
            - containerPort: 9098
          env:
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db-1:3306/ticketdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "815321#mkUMMYSQL"
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 9098
      targetPort: 9098
  type: LoadBalancer
