apiVersion: v1
kind: Pod
metadata:
  name: basicwebpodforkube
spec:
  containers:
  - name: basicwebpodforkube
    image: niraj1405/basicweb:1.0.0-2
    ports:
    - containerPort: 8098  # Port exposed by the Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: basicweb-service
spec:
  selector:
    run: basicwebpod
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8098  # Port exposed by the Pod container
