apiVersion: v1
kind: Pod
metadata:
  name: kubepodlatest
  namespace: nsnew
spec:
  containers:
  - name: kubekube
    image: niraj1405/kubeservice:1.0.0-27
    ports:
    - containerPort: 8098  # Port exposed by the Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: basicweb-service
  namespace: nsnew
spec:
  selector:
    run: kubepodlatest
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8098  # Port exposed by the Pod container
