apiVersion: v1
kind: Pod
metadata:
  name: basicwebkubepodlatest
  namespace: nsnew
spec:
  containers:
  - name: basicwebkubepodlatest
    image: niraj1405/basicweb:1.0.0-29
    ports:
    - containerPort: 8098  # Port exposed by the Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: basicwebkubeservicelatest
  namespace: nsnew
spec:
  selector:
    run: basicwebkubepodlatest
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 8098  # Port exposed by the Pod container
